/*회원 테이블*/
CREATE TABLE USERBOARD(
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(100) NOT NULL UNIQUE,
  USER_PW VARCHAR2(100) NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  USER_EMAIL VARCHAR2(500) NOT NULL,
  USER_NICKNAME VARCHAR2(100),
  USER_POSTCODE NUMBER,
  USER_ADDRESS VARCHAR2(1000),
  USER_EXTRAADDRESS VARCHAR2(1000),
  USER_DETAILADDRESS VARCHAR2(1000),
  USER_REG_DATE DATE DEFAULT SYSDATE,
  USER_ABLE VARCHAR2(4) DEFAULT 'Y' CHECK(USER_ABLE IN ('Y','N')),
  USER_ROLE VARCHAR2(10) DEFAULT 'USER' CHECK(USER_ROLE IN ('ADMIN','USER'))
);



/*프로필 이미지 테이블*/
CREATE TABLE PROFILEBOARD(
  PF_NO NUMBER PRIMARY KEY,
  PF_USERNO NUMBER NOT NULL,
  PF_NAME VARCHAR2(100) NOT NULL,
  PF_SRC VARCHAR2(500),
  PF_TYPE VARCHAR2(10),
  PF_SIZE NUMBER,
  CONSTRAINT fk_pf_user FOREIGN KEY (PF_USERNO) REFERENCES USERBOARD(USER_NO) ON DELETE CASCADE
);


/* 알람 테이블 */
CREATE TABLE ALARMBOARD(
  ALARM_NO NUMBER PRIMARY KEY,
  ALARM_USERNO NUMBER NOT NULL,
  ALARM_CONTENT VARCHAR2(4000),
  ALARM_READ VARCHAR2(4) DEFAULT 'N' CHECK(ALARM_READ IN ('Y','N')),
  ALARM_DATE DATE,
  CONSTRAINT fk_alarm_user FOREIGN KEY (ALARM_USERNO) REFERENCES USERBOARD(USER_NO) ON DELETE CASCADE
);



/* 공지사항 테이블 */
CREATE TABLE NOTICEBOARD(
  NOTICE_NO NUMBER PRIMARY KEY,
  NOTICE_USERNO NUMBER NOT NULL,
  NOTICE_TITLE VARCHAR2(1000) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000),
  NOTICE_REG_DATE DATE,
  NOTICE_VIEW NUMBER
);

/* 문의 테이블 */
CREATE TABLE QABOARD(
  QA_NO NUMBER PRIMARY KEY,
  QA_USER VARCHAR2(20) NOT NULL,
  QA_TITLE VARCHAR2(1000) NOT NULL,
  QA_CONTENT VARCHAR2(4000),
  QA_EMAIL VARCHAR2(500) NOT NULL,
  QA_DATE DATE,
  QA_CONFIRM VARCHAR2(4) DEFAULT 'N' CHECK(QA_CONFIRM IN ('Y','N'))
);


/* 신고 테이블 */ 
CREATE TABLE REPORTBOARD(
  REPORT_NO NUMBER PRIMARY KEY,
  REPORT_REASON VARCHAR2(1000) NOT NULL,
  REPORT_CONTENT VARCHAR2(4000) NOT NULL,
  REPORT_USERNO NUMBER NOT NULL,
  REPORT_TARGET_USERNO NUMBER NOT NULL,
  REPORT_DATE DATE,
  REPORT_DONE_DATE DATE,
  REPORT_CONFIRM VARCHAR2(4) DEFAULT 'N' CHECK(REPORT_CONFIRM IN ('Y','N'))
);


/* 여행지 테이블 */
CREATE TABLE TOURBOARD(
  CONTENTID NUMBER NOT NULL,
  CONTENTTYPEID NUMBER NOT NULL,
  TOUR_VIEW NUMBER,
  PRIMARY KEY(CONTENTID,CONTENTTYPEID)
);

/* 여행지 좋아요(LIKE TOUR) 테이블 */
CREATE TABLE LTBOARD(
  CONTENTID NUMBER NOT NULL,
  CONTENTTYPEID NUMBER NOT NULL,
  LT_USERNO NUMBER NOT NULL,
  PRIMARY KEY(CONTENTID,CONTENTTYPEID,LT_USERNO),
  CONSTRAINT fk_tour_like_user FOREIGN KEY (LT_USERNO) REFERENCES USERBOARD(USER_NO) ON DELETE CASCADE
);

/* 여행지 리뷰(TOUR REVIEW) */
CREATE TABLE TRBOARD(
  TR_NO NUMBER PRIMARY KEY,
  TR_USERNO NUMBER NOT NULL,
  CONTENTID NUMBER,
  CONTENTTYPEID NUMBER,
  TR_CONTENT VARCHAR2(2000),
  TR_DATE DATE
);

/* 여행코스(TOUR COURSE) 테이블 */
CREATE TABLE TCBOARD(
 TC_NO NUMBER PRIMARY KEY,
 TC_USERNO NUMBER NOT NULL,
 TC_TITLE VARCHAR2(1000) NOT NULL,
 TC_DAYS NUMBER,
 TC_DAY NUMBER,
 TC_REGION VARCHAR2(100),
 PRE_CONTENTID NUMBER,
 NEXT_CONTENTID NUMBER,
 CONTENTID NUMBER,
 CONTENTTYPEID NUMBER,
 TC_DATE DATE,
 TC_VIEW NUMBER,
 CONSTRAINT fk_tour_course_user FOREIGN KEY (TC_USERNO) REFERENCES USERBOARD(USER_NO) ON DELETE CASCADE
);


/* 찜한 여행코스(LIKE TOUR COURSE) 테이블 */
CREATE TABLE LTCBOARD(
  LTC_TCNO NOT NULL,
  LTC_USERNO NOT NULL,
  LTC_DATE DATE,
  PRIMARY KEY(LTC_TCNO,LTC_USERNO),
  CONSTRAINT fk_ltc_user FOREIGN KEY (LTC_USERNO) REFERENCES USERBOARD(USER_NO) ON DELETE CASCADE,
  CONSTRAINT fk_ltc_course FOREIGN KEY (LTC_TCNO) REFERENCES TCBOARD(TC_NO) ON DELETE CASCADE
);

/* 여행코스 리뷰(TOUR COURSE REVIEW) */
CREATE TABLE TCRBOARD(
  TCR_NO NUMBER PRIMARY KEY,
  TCR_TCNO NUMBER NOT NULL,
  TCR_USERNO NUMBER NOT NULL,
  TR_CONTENT VARCHAR2(2000),
  TR_DATE DATE,
  CONSTRAINT fk_tcr_course FOREIGN KEY (TCR_TCNO) REFERENCES TCBOARD(TC_NO) ON DELETE CASCADE
);

/* 여행코스 포스트잇(TOUR COURSE POSTIT) 테이블 */
CREATE TABLE TCPBOARD(
  TCP_NO NUMBER PRIMARY KEY,
  TCP_TCNO NUMBER NOT NULL,
  TCP_USERNO NUMBER NOT NULL,
  CONTENTID NUMBER NOT NULL,
  CONTENTTYPEID NUMBER,
  TCP_CONTENT  VARCHAR2(2000) NOT NULL,
  TCP_DATE DATE,
  CONSTRAINT fk_tcp_course FOREIGN KEY (TCP_TCNO) REFERENCES TCBOARD(TC_NO) ON DELETE CASCADE
);



INSERT INTO USERBOARD(USER_NO,USER_ID,USER_PW,USER_NAME,USER_EMAIL,USER_ROLE)
VALUES(0,'ADMIN','ADMIN','관리자','ADMIN@ADMIN.CO.KR','ADMIN');

/*
DROP TABLE LTCBOARD;
DROP TABLE LTBOARD;
DROP TABLE TOURBOARD;

DROP TABLE TCPBOARD;
DROP TABLE TCRBOARD;
DROP TABLE TCBOARD;

DROP TABLE PROFILEBOARD;
DROP TABLE ALARMBOARD;
DROP TABLE USERBOARD;
DROP TABLE REPORTBOARD;
DROP TABLE QABOARD;
DROP TABLE NOTICEBOARD;

*/